import Image from "next/image";

export default function Sobre() {
  return <main><section className="page-hero about-hero"><div className="wrap page-hero-inner"><p className="eyebrow light">Nossa história</p><h1>24 anos de<br /><em>muita beleza.</em></h1><p>Experiência que evolui. Cuidado que permanece.</p></div></section>
    <section className="section wrap story-grid"><div><p className="eyebrow">Visual Spa Hair</p><h2>Um salão feito de relações, confiança e transformação.</h2></div><div><p>Há 24 anos, fazemos da beleza uma forma de cuidado. Em cada atendimento, unimos conhecimento técnico, atenção genuína e respeito pela individualidade de quem chega até nós.</p><p>Estamos no coração de Foz do Iguaçu para acompanhar mudanças, celebrar fases e criar resultados que fazem sentido na vida real — bonitos no salão e possíveis na rotina.</p></div></section>
    <section className="values section"><div className="wrap value-grid"><article><span>01</span><h3>Escuta</h3><p>Antes de qualquer técnica, entendemos você, seu histórico e seus desejos.</p></article><article><span>02</span><h3>Cuidado</h3><p>A saúde dos fios orienta as decisões e os caminhos de cada transformação.</p></article><article><span>03</span><h3>Experiência</h3><p>24 anos de prática, atualização e compromisso com resultados consistentes.</p></article><article><span>04</span><h3>Identidade</h3><p>Beleza não é fórmula pronta. Cada resultado é pensado para ser verdadeiramente seu.</p></article></div></section>
    <section className="section wrap image-statement"><div className="statement-image"><Image src="/media/IMG-20240621-WA0040.jpg.jpeg" alt="Resultado de penteado no Visual Spa Hair" fill sizes="(max-width: 850px) 100vw, 52vw" /></div><div><p className="eyebrow">Nossa prioridade</p><blockquote>“Realçar a sua beleza, sem apagar aquilo que faz você ser você.”</blockquote><a className="text-link" href="https://www.instagram.com/visual_spahair/" target="_blank" rel="noreferrer">Acompanhe nosso dia a dia <span>↗</span></a></div></section>
  </main>;
}
