import { waLink } from "../whatsapp";

const groups = [
  { index:"01", title:"Cor", items:[["Coloração", "Aplicação global, retoque de raiz e renovação de cor."],["Mechas", "Iluminação personalizada, loiros e morena iluminada."],["Correção de cor", "Avaliação do histórico e planejamento técnico antes do procedimento."]]},
  { index:"02", title:"Forma", items:[["Cortes", "Corte feminino, masculino e infantil, com acabamento personalizado."],["Progressiva", "Alinhamento dos fios com indicação conforme o diagnóstico."],["Escova", "Preparação e acabamento para rotina ou ocasião especial."],["Penteado", "Produção para festas, formaturas, casamentos e eventos."],["Make", "Maquiagem para eventos, ensaios e ocasiões especiais."]]},
  { index:"03", title:"Extensão", items:[["Manutenção de mega hair", "Reposicionamento, acabamento e orientação de cuidados."],["Avaliação", "Análise da extensão, couro cabeludo e condição dos fios naturais."]]},
  { index:"04", title:"Saúde capilar", items:[["Tricoscopia", "Exame do couro cabeludo e dos fios para diagnóstico preciso."],["Consultoria capilar", "Orientação individual sobre rotina, produtos e cuidados."],["Tratamentos", "Hidratação, nutrição e reconstrução conforme a necessidade."],["Alopecias, psoríase e dermatites", "Acompanhamento de condições do couro cabeludo com terapia capilar."],["Quedas capilares", "Protocolo de cuidado para fortalecimento e redução da queda."],["Terapia capilar feminina", "Cuidado direcionado ao couro cabeludo e aos fios."],["Terapia capilar masculina", "Avaliação e protocolo de cuidado para homens."]]},
];
export default function Servicos(){return <main><section className="inner-mast services-mast"><div className="wrap"><p className="overline light">Menu de serviços</p><h1>Técnica para<br /><i>cada cabelo.</i></h1><p>Os procedimentos são indicados após avaliação. Valores e duração variam conforme comprimento, volume e condição dos fios.</p></div></section><section className="service-menu section wrap"><div className="menu-aside"><p className="overline">Atendimento</p><h2>Converse antes de escolher.</h2><p>Se você não sabe qual serviço agendar, envie uma foto atual e uma referência pelo WhatsApp. A equipe orienta o melhor primeiro passo.</p><a className="solid-button" href={waLink("Olá! Gostaria de uma orientação sobre qual serviço agendar.")} target="_blank" rel="noreferrer">Pedir orientação</a></div><div className="menu-groups">{groups.map(group=><article className="menu-group" key={group.index}><header><span>{group.index}</span><h2>{group.title}</h2></header>{group.items.map(([name,desc])=><div className="menu-item" key={name}><h3>{name}</h3><p>{desc}</p><a href={waLink(`Olá! Gostaria de informações sobre ${name}.`)} target="_blank" rel="noreferrer">Consultar</a></div>)}</article>)}</div></section><section className="service-note"><div className="wrap"><b>Importante</b><p>Procedimentos químicos podem exigir teste de mecha e avaliação presencial antes do agendamento definitivo.</p></div></section></main>}
